### ISSUE TITLE
Your site is at risk

### ISSUE THREAD

**Issue by ahinkle** [MiniProf/ProfServerPush#1]
Hi,

I would like to let you know your FTP credentials is publicly available. Please remove the .ftpconfig and add it to your .gitignore.

`{
    "protocol": "sftp",
    "host": "******************* AVAILABLE FOR EVERYONE TO SEE  ***********",
    "port": 6767,
    "user": "******************* AVAILABLE FOR EVERYONE TO SEE  ***********",
    "pass": "******************* AVAILABLE FOR EVERYONE TO SEE  ***********",
    "promptForPass": true,
    "remote": "/home/lancs/wilsong4/PushServer/",
    "local": "",
    "agent": "",
    "privatekey": "",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false,
    "watch": [],
    "watchTimeout": 500
}`

**Comment by GeorgeWilson96** [comment]
Thank you for this! the pass was invalid anyway but. Thank you very much for pointing this out!
